CREATE TABLE `PROMOTION` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOM` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `GROUPE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOM` varchar(255) NOT NULL,
	`ID_GROUPE` INT(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ETUDIANT` (
	`ID_UTILISATEUR` varchar(255) NOT NULL,
	`NUMERO` INT NOT NULL,
	`ID_GROUPE` INT NOT NULL,
	PRIMARY KEY (`ID_UTILISATEUR`)
);

CREATE TABLE `UTILISATEUR` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`EMAIL` varchar(255) NOT NULL,
	`PASSWD` varchar(255) NOT NULL,
	`NOM` varchar(255) NOT NULL,
	`PRENOM` varchar(255) NOT NULL,
	`DROIT` INT(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `COURS` (
	`ID` INT NOT NULL,
	`NOM` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TYPE_COURS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOM` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ENSEIGNANT` (
	`ID_UTILISATEUR` INT NOT NULL AUTO_INCREMENT,
	`ID_COURS` INT NOT NULL,
	PRIMARY KEY (`ID_UTILISATEUR`,`ID_COURS`)
);

CREATE TABLE `SITE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOM` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SALLE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOM` varchar(255) NOT NULL,
	`CAPACITE` INT(255) NOT NULL,
	`ID_SITE` INT(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SEANCE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`SEMAINE` INT NOT NULL,
	`DATE` DATETIME NOT NULL,
	`HEURE_DEBUT` DATETIME NOT NULL,
	`HEURE_FIN` DATETIME NOT NULL,
	`ETAT` INT NOT NULL,
	`ID_COURS` INT NOT NULL,
	`ID_TYPE` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SEANCE_GROUPES` (
	`ID_SEANCE` INT NOT NULL AUTO_INCREMENT,
	`ID_GROUPE` INT NOT NULL,
	PRIMARY KEY (`ID_SEANCE`,`ID_GROUPE`)
);

CREATE TABLE `SEANCE_ENSEIGNANTS` (
	`ID_SEANCE` INT NOT NULL AUTO_INCREMENT,
	`ID_ENSEIGNANT` INT NOT NULL,
	PRIMARY KEY (`ID_SEANCE`,`ID_ENSEIGNANT`)
);

CREATE TABLE `SEANCE_SALLES` (
	`ID_SEANCE` INT NOT NULL,
	`ID_SALLE` INT NOT NULL,
	PRIMARY KEY (`ID_SEANCE`)
);

ALTER TABLE `GROUPE` ADD CONSTRAINT `GROUPE_fk0` FOREIGN KEY (`ID_GROUPE`) REFERENCES `PROMOTION`(`ID`);

ALTER TABLE `ETUDIANT` ADD CONSTRAINT `ETUDIANT_fk0` FOREIGN KEY (`ID_UTILISATEUR`) REFERENCES `UTILISATEUR`(`ID`);

ALTER TABLE `ETUDIANT` ADD CONSTRAINT `ETUDIANT_fk1` FOREIGN KEY (`ID_GROUPE`) REFERENCES `GROUPE`(`ID`);

ALTER TABLE `ENSEIGNANT` ADD CONSTRAINT `ENSEIGNANT_fk0` FOREIGN KEY (`ID_UTILISATEUR`) REFERENCES `UTILISATEUR`(`ID`);

ALTER TABLE `ENSEIGNANT` ADD CONSTRAINT `ENSEIGNANT_fk1` FOREIGN KEY (`ID_COURS`) REFERENCES `COURS`(`ID`);

ALTER TABLE `SALLE` ADD CONSTRAINT `SALLE_fk0` FOREIGN KEY (`ID_SITE`) REFERENCES `SITE`(`ID`);

ALTER TABLE `SEANCE` ADD CONSTRAINT `SEANCE_fk0` FOREIGN KEY (`ID_COURS`) REFERENCES `COURS`(`ID`);

ALTER TABLE `SEANCE` ADD CONSTRAINT `SEANCE_fk1` FOREIGN KEY (`ID_TYPE`) REFERENCES `TYPE_COURS`(`ID`);

ALTER TABLE `SEANCE_GROUPES` ADD CONSTRAINT `SEANCE_GROUPES_fk0` FOREIGN KEY (`ID_SEANCE`) REFERENCES `SEANCE`(`ID`);

ALTER TABLE `SEANCE_GROUPES` ADD CONSTRAINT `SEANCE_GROUPES_fk1` FOREIGN KEY (`ID_GROUPE`) REFERENCES `GROUPE`(`ID`);

ALTER TABLE `SEANCE_ENSEIGNANTS` ADD CONSTRAINT `SEANCE_ENSEIGNANTS_fk0` FOREIGN KEY (`ID_SEANCE`) REFERENCES `SEANCE`(`ID`);

ALTER TABLE `SEANCE_ENSEIGNANTS` ADD CONSTRAINT `SEANCE_ENSEIGNANTS_fk1` FOREIGN KEY (`ID_ENSEIGNANT`) REFERENCES `ENSEIGNANT`(`ID_UTILISATEUR`);

ALTER TABLE `SEANCE_SALLES` ADD CONSTRAINT `SEANCE_SALLES_fk0` FOREIGN KEY (`ID_SEANCE`) REFERENCES `SEANCE`(`ID`);

ALTER TABLE `SEANCE_SALLES` ADD CONSTRAINT `SEANCE_SALLES_fk1` FOREIGN KEY (`ID_SALLE`) REFERENCES `SALLE`(`ID`);

