/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import DAO.CoursDAO;
import DAO.EnseignantDAO;
import DAO.SalleDAO;
import DAO.SeanceDAO;
import DAO.Seance_SallesDAO;
import DAO.SiteDAO;
import DAO.UtilisateurDAO;
import Modele.Cours;
import Modele.Enseignant;
import Modele.Salle;
import Modele.Seance;
import Modele.Seance_Salles;
import Modele.Site;
import Modele.Utilisateur;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *Affiche la liste de toutes les classes

 */
public class ListeEnseignant extends javax.swing.JFrame {

    
    static ArrayList<Cours> cours1=new ArrayList();
    static CoursDAO coursDAO;
    static Cours cours =new Cours();
    AddCoursV2 addCoursV2=new AddCoursV2();
    
    
    static ArrayList<Utilisateur> util1=new ArrayList();
    
    static ArrayList<Enseignant> enseign1=new ArrayList();
    static EnseignantDAO enseignDAO;
    static Enseignant enseign =new Enseignant();
    AddEnseignant addenseign = new AddEnseignant();
    
    //AddCours addCours=new AddCours();
    
    //static ArrayList<Niveau> allLevels=new ArrayList<Niveau>();
    //static ArrayList<AnneeScolaire>allYears=new ArrayList<AnneeScolaire>();
    
    static DefaultTableModel modelListeEnseignant;

    
    
    
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//fillCours2();
	}
	
    /**
     * Creates new form Classes
     */
    public ListeEnseignant(){
        initComponents();          
        modelListeEnseignant=(DefaultTableModel) jTable1.getModel();
        addenseign =new AddEnseignant(); //On récupère les cours
        fill ();
        
        
    }
    
    /**
     * Remplit l'mploi du temps avec celles trouvées dans la bdd, version graphique
     */
    public void fill(){
        try {          
        	
        	
            EnseignantDAO enseignDAO= new EnseignantDAO();
            UtilisateurDAO utilDAO = new UtilisateurDAO();
            
            coursDAO=new CoursDAO();
            cours1 = coursDAO.all();
            
            
        	enseignDAO = new EnseignantDAO();
            enseign1=enseignDAO.all(); //Récupère toutes les lignes de la table cours
            
            enseignDAO= new EnseignantDAO();
            enseign1=enseignDAO.all();
            
            
            utilDAO = new UtilisateurDAO();
            util1 = utilDAO.all();

            
            String nom = "";
            String prenom = "";
            String nom_cours = "";
            
           
            pack();
            
            
            
            System.out.println("fill");
            for(int i=0;i<enseign1.size();i++){

            	
                int id_enseignant=enseign1.get(i).getId_utilisateur();
                int id_cours= enseign1.get(i).getId_cours();
                
       		 	
                
                for(int j=0;j<util1.size();j++){
                	 int id_utilisateur=util1.get(j).getId();
                	 if(id_enseignant == id_utilisateur)
                	 {
                		 nom = util1.get(j).getNom();
                		 prenom = util1.get(j).getPrenom();
                	 }
                }
                
                for(int k=0;k<cours1.size();k++){
               	 int idducours=cours1.get(k).getId();
               	 	System.out.println(idducours);
	               	 if(id_cours == idducours)
	               	 {
	               		 nom_cours = cours1.get(k).getNom();
	
	               	 }
                }
                
                //Cree l'object à mettre dans le model
                Object[]cls={id_enseignant,id_cours,nom,prenom,nom_cours};
                
               modelListeEnseignant.insertRow(modelListeEnseignant.getRowCount(), cls);                
               //enseign1.get(i).afficher(); //affichage console                
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Il semblerait qu'une erreur soit survenue.");
        }
    }
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * ===========================================================================
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
       
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1 = new javax.swing.JTextField();
        jTextField1.setText("Rechercher");

        jTable1 = new javax.swing.JTable();
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"Id_utilisateur","Id_cours","Nom","Prenom","Cours"}) 
        {boolean[] canEdit = new boolean [] {false,true,true,true,true};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setViewportView(jTable1);

        add = new javax.swing.JButton();
        add.setText("Ajouter");
      
        delete = new javax.swing.JButton();
        delete.setText("Supprimer");
        
        update = new javax.swing.JButton();
        update.setText("Modifier");
       
        displaySeances = new javax.swing.JButton();
        displaySeances.setText("Afficher les séances");
        
        jButtonRetour = new javax.swing.JButton();
        jButtonRetour.setText("Retour");
      

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonRetour)
                        .addGap(262, 262, 262)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(add)
                        .addGap(152, 152, 152)
                        .addComponent(delete)
                        .addGap(175, 175, 175)
                        .addComponent(update)
                        .addGap(150, 150, 150)
                        .addComponent(displaySeances)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetour)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(displaySeances))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
        
        
        
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });
        
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        
        
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //updateActionPerformed(evt);
            }
        });
        
        displaySeances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaySeancesActionPerformed(evt);
            }
        });

    }// </editor-fold>//GEN-END:initComponents

    
        /**
     *Cherche une année dans l'arraylist avec un id
     * @param id_annee
     * @return
     *
    public static AnneeScolaire findYear(int id_annee){
        AnneeScolaire annee=new AnneeScolaire();
        for(int i=0;i<allYears.size();i++){
                if(allYears.get(i).getId_anneeScolaire()==id_annee)
                    annee=new AnneeScolaire(allYears.get(i).getId_anneeScolaire());
            }
        return annee; 
    } */
    
    /**
     *Cherche un niveau dans l'arraylist avec un nom de niveau
     * @param nom_niveau
     * @return
     *
    public static Niveau findLevel(String nom_niveau){
        
        Niveau niveau=new Niveau();
        for(int i=0;i<allLevels.size();i++){
                if(allLevels.get(i).getNom().equals(nom_niveau)){
                   
                    niveau=new Niveau(allLevels.get(i).getId_niveau(),allLevels.get(i).getNom());
                }
                
            } 
        
        return niveau;
    }
    */
    
    
    
    


 
    //Retour
    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
        Menu menu=new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    
    
    //Ajouter un cours
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
    	
    	AddEnseignant addenseign = new AddEnseignant();
        addenseign.setVisible(true);
     
        dispose(); //ferme et réouvre la page ce qui actualise la table
        
        ListeEnseignant listeenseign1=new ListeEnseignant();
        listeenseign1.setVisible(true);
    }//GEN-LAST:event_ajouterActionPerformed
    
    
    
    
    //Supprimer un cours
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         try {
             
            if(jTable1.getSelectedRow()==-1){//Si aucune ligne est selectionnee
                if(modelListeEnseignant.getRowCount()==0){
                    JOptionPane.showMessageDialog(rootPane, "Le tableau est vide.");                  
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Selectionner une ligne.");
                }  
            }
            else{
               
                enseign=new Enseignant();
                enseignDAO=new EnseignantDAO();
                
                Utilisateur util = new Utilisateur();
                UtilisateurDAO utilDAO = new UtilisateurDAO();
                
                

                int currentRow=jTable1.getSelectedRow();

                int id=(int) modelListeEnseignant.getValueAt(currentRow,0);//Récupère l'Id de la ligne selectionné
                
                System.out.println(id);
                enseign=enseignDAO.find(id); //Trouver la personne dans la bdd avec l'id
                util = utilDAO.find(id);

                
                //Demande de confirmation
                int confirm=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer "+cours.getNom()+" d'ID: "+id+" ?");
                if(confirm==JOptionPane.YES_OPTION){                   
                    enseignDAO.delete(enseign); //Enlever de la bdd
                    enseignDAO.deleteId(id); //Enlever de la bdd
                    utilDAO.deleteId(id);
                    modelListeEnseignant.removeRow(currentRow); 
                    
                    enseign1=enseignDAO.all(); //On remet Ã  jour l'arraylist 
                    JOptionPane.showMessageDialog(null, "L'enseignant "+enseign.getId_utilisateur()+" a été supprimé.");             
                }

            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Une erreur est survenue");
        }
    }//GEN-LAST:event_deleteActionPerformed

    
    
    
    /**
     *Instancie et retourne une classe en selectionnant sa ligne dans le tableau
     */
    public Enseignant selectEnseignant(){
        
        Enseignant enseign=new Enseignant();
        //On rÃ©cup toutes la ligne puis instanciation Ã  partir de l'arraylist.
            int currentRow=jTable1.getSelectedRow();
            
            
            int id_utilisateur=(int)modelListeEnseignant.getValueAt(currentRow,0);           
            int id_cours = 0;
            
            //Instanciation de la classe modifiÃ©e
            enseign=new Enseignant(id_utilisateur,id_cours);           
            return enseign;   
    }
    /*
    //Modifier une classe
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            // TODO add your handling code here:
            
            classe=new Classe();
            classeDAO=new ClasseDAO();
            
            //Si aucune ligne n'est sÃ©lectionnÃ©e...
            if(jTable1.getSelectedRow()==-1){
                if(modelClass.getRowCount()==0){
                    JOptionPane.showMessageDialog(rootPane, "Le tableau est vide.");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "SÃ©lectionner une ligne.");
                }
            }
            
            else{
                classe=selectClass();                     
                System.out.println("classe modifiee:");
                classe.afficher();
          
            
            if(classe.equals(classeDAO.update(classe))){           
                JOptionPane.showMessageDialog(rootPane, "Modification effectuÃ©e avec succÃ¨s.");  
                classes=classeDAO.all(); //On remet Ã  jour l'arraylist de classes depuis la bdd
            }
            else{
                System.out.println("oups");
            }
            
            
            
        }
            
            } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Il semblerait qu'une erreur soit survenue.");
        }
    }//GEN-LAST:event_updateActionPerformed
*/
    
    //Afficher les infos de la classe sÃ©lectionnÃ©e
     
    private void displaySeancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStudentsActionPerformed
        // TODO add your handling code here:
        
        //Si aucune ligne n'est sÃ©lectionnÃ©e...
        if(jTable1.getSelectedRow()==-1){
            if(modelListeEnseignant.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane, "Le tableau est vide.");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "SÃ©lectionner une ligne.");
            }
        }
        else{
        	int currentRow=jTable1.getSelectedRow();
        	int id=(int)modelListeEnseignant.getValueAt(currentRow,0);
            enseign=selectEnseignant();
            ListeSeance listeseance=new ListeSeance(id);
            listeseance.setVisible(true);
        }
             
        
    }//GEN-LAST:event_displayStudentsActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton displaySeances;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
      
     
     
}
